name: Build feature branch

on:
  push:
    branches:
      - feature/*

  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test with Maven
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Tests with Maven
        run: mvn test verify
        env:
          DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AUTH0_JWT_ISSUER: ${{ secrets.AUTH0_JWT_ISSUER }}
          WORKSHOP_CORS_ORIGINS: ${{ secrets.WORKSHOP_CORS_ORIGINS }}
